services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - "35432:5432"
    networks:
      - compose-network
    volumes:
      - nae-pg-prisma-redis-data-pg:/var/lib/postgresql/data
    shm_size: 256MB
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
  cache:
    image: redis/redis-stack:7.2.0-v10
    ports:
      - "36379:6379"
      - "38001:8001" # redis insight
    networks:
      - compose-network
    volumes:
      - nae-pg-prisma-redis-data-redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  nae-pg-prisma-redis-data-pg:
  nae-pg-prisma-redis-data-redis:
networks:
  compose-network:
